# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  (1..3).each do |i|
    config.vm.define vm_name = "cdh#{i}"  do |config|
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--name", vm_name, "--memory", "1200",'--cpus', 1]
      end
      config.vm.box = "boxcutter/centos73"
      config.vm.hostname =vm_name
      config.vm.synced_folder "#{ENV['VM_ROOT']}/software", "/root/software"
      config.vm.synced_folder "config", "/root/config"
      # config.ssh.username ="vagrant"
      # config.ssh.password="vagrant"
      config.vm.network :private_network, ip: "192.168.56.12#{i}"
      config.vm.provision :shell, :path => "bootstrap.sh",keep_color: true
      # Increase memory for Virtualbox
      if i == 1
        config.vm.provider "virtualbox" do |vb|
          vb.memory = "4096"
          vb.cpus = "1"
        end
      else
        config.vm.provider "virtualbox" do |vb|
          vb.memory = "2048"
          vb.cpus = "1"
        end
      end
    end
  end
end
